export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_CASCADE = 'DELETE_CARD_CASCADE';
export const CHANGE_CARD_HEAD = 'CHANGE_CARD_HEAD';
export const CHANGE_CARD_DESCRIPTION = 'CHANGE_CARD_DESCRIPTION';
