export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_CASCADE = 'DELETE_COMMENT_CASCADE';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
